# Generated by Django 3.2.20 on 2023-09-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_Name', models.CharField(max_length=100)),
                ('Emp_Code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Department', models.CharField(choices=[('AA', 'Accounts&Admin'), ('AS', 'Assembly'), ('CT', 'Controls'), ('CO', 'Cooking'), ('DE', 'Default'), ('DS', 'Designing'), ('EL', 'Electrical'), ('HK', 'House Keeping'), ('MA', 'Manufacturing'), ('PU', 'Purchase')], default='DE', max_length=100)),
                ('no_of_days', models.PositiveSmallIntegerField()),
                ('days_worked', models.PositiveSmallIntegerField()),
                ('Ot_hrs', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HRA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRA_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Overtime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('W_F_P', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LOP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRA_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ESI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_Card', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOTAL_gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GROSS_SALARY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOTAL_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NET_SALARY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.employee')),
            ],
        ),
    ]
