# Generated by Django 4.2.5 on 2023-09-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Ot_hrs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
