# Generated by Django 3.2.20 on 2023-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
