# Generated by Django 3.2.20 on 2023-09-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_payslip_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.IntegerField(),
        ),
    ]
